config/routes.rb
Rails.application.routes.draw do
  resources :games

  get 'search', to: 'index#search'
  post 'search/get_search', to: 'search#get_search', as: 'get_search'
  
  root "index#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/index.rb
class Index < ApplicationRecord
    
end

app/models/search.rb
def get_token
    require "uri"
    require "net/http"
    require "JSON"
  
    url = URI("https://id.twitch.tv/oauth2/token?client_id=lhfcfvbudj94sfv6171yzgn52mywub&client_secret=msuaa3xewcx6reciud88dwqu1kvp3x&grant_type=client_credentials")
  
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
  
    request = Net::HTTP::Post.new(url)
  
    response = https.request(request)
    igdb_token = JSON.parse(response.body)['access_token']
end


def search_igdb
    response = RestClient.get("https://api.igdb.com/v4/games", {
        Authorization: "Bearer #{session[:igdb_token]}",
        headers: {
            "Client-ID" => ENV["CLIENT_ID"],
            "Accept" => "application/json",
            "Content-Type" => "application/json"
        },
        params: {
            "search" => "mario",
            "fields" => "name,platforms,genres,cover.url"
        }
        })
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:artworks, :name, :platforms, :release_dates, :screenshots, :summary, :genre, :total_rating)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

def Index
end

def search
    
end

def contact
end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    require 'apicalypse'
    require "uri"
    require "net/http"
    require "json"
   

    def get_token
      
        url = URI("https://id.twitch.tv/oauth2/token?client_id=#{ENV[client_id]}&client_secret=msuaa3xewcx6reciud88dwqu1kvp3x&grant_type=client_credentials")
      
        https = Net::HTTP.new(url.host, url.port)
        https.use_ssl = true
      
        request = Net::HTTP::Post.new(url)
      
        response = https.request(request)
        igdb_token = JSON.parse(response.body)['access_token']
        @@igdb_token= igdb_token
    end


    
         
    def get_search
   
        url = URI("https://api.igdb.com/v4/games/")
        
        https = Net::HTTP.new(url.host, url.port)
        https.use_ssl = true
        
        request = Net::HTTP::Post.new(url)
        request["Client-ID"] = "lhfcfvbudj94sfv6171yzgn52mywub"
        request["Authorization"] = "Bearer 3gavt6s2f0iwtf6hkbsem7ue7l68dl" 
        request["Content-Type"] = "text/plain"
        request.body = "fields name, artworks, screenshots, genres, summary, platforms, release_dates; search \"#{:gamequery}\"; limit 50;"
        
        response = https.request(request)
        @game = JSON.parse(response.body)
        redirect_to search_path
    end
   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/post_request_to_igdb_helper.rb
module PostRequestToIgdbHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :artworks, style: "display: block" %>
    <%= form.number_field :artworks %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :platforms, style: "display: block" %>
    <%= form.number_field :platforms %>
  </div>

  <div>
    <%= form.label :release_dates, style: "display: block" %>
    <%= form.number_field :release_dates %>
  </div>

  <div>
    <%= form.label :screenshots, style: "display: block" %>
    <%= form.number_field :screenshots %>
  </div>

  <div>
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_area :summary %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.number_field :genre %>
  </div>

  <div>
    <%= form.label :total_rating, style: "display: block" %>
    <%= form.text_field :total_rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Artworks:</strong>
    <%= game.artworks %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= game.name %>
  </p>

  <p>
    <strong>Platforms:</strong>
    <%= game.platforms %>
  </p>

  <p>
    <strong>Release dates:</strong>
    <%= game.release_dates %>
  </p>

  <p>
    <strong>Screenshots:</strong>
    <%= game.screenshots %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= game.summary %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= game.genre %>
  </p>

  <p>
    <strong>Total rating:</strong>
    <%= game.total_rating %>
  </p>

</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Games</h1>

<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <%= link_to "Edit this game", edit_game_path(@game) %> |
  <%= link_to "Back to games", games_path %>

  <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/index/index.html.erb
    <%= render "partials/landing" %>

app/views/index/search.html.erb
<div class="landing">
<h1 class="title">Search Results</h1>

    <%= render "partials/gameCard" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamer Backlog</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="/assets/small-logo.ico" rel="shortcut icon" type="image/x-icon" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= render "partials/nav" %>
    <main>
    <%= yield %>

    </main>
    <%= render "partials/footer" %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer>
    <div class="row">
        <a href="#" class="footer__anchor">
            <figure>
                <img src="./assets/white-backlog.png" alt="Backlog Logo">
            </figure>
            <span class="footer__anchor--popper">
                Top
                <i class="fas fa-arrow-up"></i>
            </span>
        </a>
        <div class="footer__social--list">
            <%= link_to "Home", root_path, class:"
            footer__social--link
            link__hover-effect
            link__hover-effect--white",
            target:"_blank"
            %>
        
            <%= link_to "Find Your Game", search_path, class:"
            footer__social--link
            link__hover-effect
            link__hover-effect--white",
            target:"_blank"
            %>
        
            <%= link_to "Sign In / Up", "#", class:"
            btn no-cursor
            footer__social--link
            link__hover-effect
            link__hover-effect--white",
            target:"_blank"
            %>
        
             <%= link_to "Contact", "#", class:"
            btn no-cursor
            footer__social--link
            link__hover-effect
            link__hover-effect--white"
            %>
        </div>
        <p>Copyright ©2022 Chris Hayes</p>
    </div>
</footer>

app/views/partials/_gameCard.html.erb
<h2> this is a game card for the game "<%= @game.each { |x| puts x["name"]} %>" </h2>

app/views/partials/_landing.html.erb
<div class="landing">
    <div class="landing__container--img"> </div>
    <div class="container__logo--animation">
        <img src="./assets/logo_controller.svg" class="ladinglogo">
        <img src="./assets/logo_background.svg" class="ladinglogo delay--1">
        <img src="./assets/logo_outline.svg" class="ladinglogo delay--2">
    </div>
</div>

app/views/partials/_nav.html.erb
<header>
    <div class="container__top">
        <div class="logo__container flex">
            <img src="./assets/small-logo.png" alt="Backlog Icon">
            <h1>Video Games Directory</h1>
        </div>
        <nav>
            <ul>
                <li> <%= link_to "Home", root_path%></li>
                <li> <%= link_to "Find Your Game", search_path%></li>
                <li> <%= link_to "Sign In / Up", "#", class:"btn no-cursor"%></li>
            </ul>
        </nav>  
    </div>
    <%= render "partials/search_header"%>
</header>

app/views/partials/_results.html.erb
<div class="search--show">
       <div class="results">
           <h2>Search Results</h2>
           <div class="card--container">
            <div class="card--game">
                    <img src="./assets/BOTW-card.jpeg" alt="">
                    <h3 class="title">GameTitle</h3>
                    <p class="game--description">Breath of the wild is the open world entry into the zelda series.</p><p>Playable on ||Platforms||.</p>
                    <div class="container--ratings">*****</div>
                    
                </div>
            <div class="card--game">
                <img src="./assets/BOTW-card.jpeg" alt="">
                <h3 class="title">GameTitle</h3>
                <p class="game--description">Breath of the wild is the open world entry into the zelda series. </p><p>Playable on ||Platforms||.</platforms></p>
                <div class="container--ratings">*****</div>
                
            </div><div class="card--game">
                <img src="./assets/BOTW-card.jpeg" alt="">
                <h3 class="title">GameTitle</h3>
                <p class="game--description">Breath of the wild is the open world entry into the zelda series.</p><p>Playable on ||Platforms||.</p>
                <div class="container--ratings">*****</div>
                
            </div><div class="card--game">
                    <img src="./assets/BOTW-card.jpeg" alt="">
                    <h3 class="title">GameTitle</h3>
                    <p class="game--description">Breath of the wild is the open world entry into the zelda series.</p><p>Playable on ||Platforms||.</p>
                    <div class="container--ratings">*****</div>
                    
                </div>
            <div class="card--game">
                    <img src="./assets/BOTW-card.jpeg" alt="">
                    <h3 class="title">GameTitle</h3>
                    <p class="game--description">Breath of the wild is the open world entry into the zelda series.</p><p>Playable on ||Platforms||.</p>
                    <div class="container--ratings">*****</div>
                    
                </div>
            <div class="card--game">
                <img src="./assets/BOTW-card.jpeg" alt="">
                <h3 class="title">GameTitle</h3>
                <p class="game--description">Breath of the wild is the open world entry into the zelda series. </p><p>Playable on ||Platforms||.</platforms></p>
                <div class="container--ratings">*****</div>
                
            </div><div class="card--game">
                <img src="./assets/BOTW-card.jpeg" alt="">
                <h3 class="title">GameTitle</h3>
                <p class="game--description">Breath of the wild is the open world entry into the zelda series.</p><p>Playable on ||Platforms||.</p>
                <div class="container--ratings">*****</div>
                
            </div><div class="card--game">
                    <img src="./assets/BOTW-card.jpeg" alt="">
                    <h3 class="title">GameTitle</h3>
                    <p class="game--description">Breath of the wild is the open world entry into the zelda series.</p><p>Playable on ||Platforms||.</p>
                    <div class="container--ratings">*****</div>
                    
                </div>
            </div>
       </div>
    </div>

app/views/partials/_search_header.html.erb
<div class="search__container">
    <div class="alert__container">
      <% if flash[:alert] %>
        <div class="alert__message"><%= flash[:alert] %></div>
      <% end %>
      <div class="mx-auto mt-5" style="width: 400px"></div>

    <%= form_with url: get_search_path, method: :post do |form| %> 
    <%= form.label :gamequery, "Search for:" %>
    <%= form.text_field :gamequery, placeholder: 'Mario' %>
    <%= form.submit "Search" %>
    <% end %>
    <button class="btn__search">
            <img src="./assets/tiny-search.png" >
        </button>
    
</div>      